### ISSUE TITLE
[BUG]: 9.10.47 crashes on startup due to missing DepLoader class

### ISSUE THREAD

**Issue by erialsan** [Thorfusion/Mekanism-Community-Edition#243]
### Describe the bug

After updating from 9.10.46 to 9.10.47, the game crashes on startup. The changelog mentions "Removed deploader & hardcoded dependencies", but LoadingHook.java still references codechicken.core.launch.DepLoader, causing a NoClassDefFoundError

### To Reproduce

1.Install Mekanism-Community-Edition 9.10.47
2.Launch the game
3.Crash occurs immediately on startup

### Expected behavior

Game launches successfully as it did with 9.10.46.

### Mekanism Version

9.10.47

### Minecraft Version is this regarding?

1.7.10

### What OS are you seeing the problem on?

Linux

### The crash report in folder ./crash-reports (both server and client logs)

```shell
https://mclo.gs/OAKjr2b

java.lang.NoClassDefFoundError: codechicken/core/launch/DepLoader
	at mekanism.common.asm.LoadingHook.<init>(LoadingHook.java:12)
Caused by: java.lang.ClassNotFoundException: Class bytes are null for codechicken.core.launch.DepLoader
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:326)
```

**Comment by erialsan** [comment]
used GTNH cccore

**Comment by DDRAIGOCH117** [comment]
I do use GTNH Code Chicken Core and i'm still getting this issue. Weird behavior indeed.

**Comment by maggi373** [comment]
> I do use GTNH Code Chicken Core and i'm still getting this issue. Weird behavior indeed.

@DDRAIGOCH117 9.10.47 is a broken build, use 46 now or 48 in tommorrow ish

**Comment by DDRAIGOCH117** [comment]
Thanks for the feedback! I downgraded to 46 and everything works correctly.
